"""Added Token column

Revision ID: 435b09502b8c
Revises: d01e2671de0e
Create Date: 2024-02-18 00:36:11.514031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435b09502b8c'
down_revision = 'd01e2671de0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Token', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('Token')

    # ### end Alembic commands ###
