"""empty message

Revision ID: 6d9291e0871b
Revises: bf7d584153d7
Create Date: 2024-02-28 01:50:31.332275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9291e0871b'
down_revision = 'bf7d584153d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_categories',
    sa.Column('CategoryID', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('max_limit', sa.Integer(), nullable=False),
    sa.Column('ticket_sold', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('EventID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['EventID'], ['events.EventID'], ),
    sa.PrimaryKeyConstraint('CategoryID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_categories')
    # ### end Alembic commands ###
