"""Added ticket in event

Revision ID: b1a649714b81
Revises: 435b09502b8c
Create Date: 2024-02-19 15:33:14.642732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a649714b81'
down_revision = '435b09502b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EventID', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'events', ['EventID'], ['EventID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('EventID')

    # ### end Alembic commands ###
