"""empty message

Revision ID: b6c8c914533b
Revises: a1319d7fdcfa
Create Date: 2024-03-26 03:34:21.783244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c8c914533b'
down_revision = 'a1319d7fdcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_sales', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resold_tickets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_resold_revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('resold_revenue_share_to_business', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_revenue', sa.Float(), nullable=True))
        batch_op.drop_column('ticket_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_revenue')
        batch_op.drop_column('resold_revenue_share_to_business')
        batch_op.drop_column('total_resold_revenue')
        batch_op.drop_column('resold_tickets')
        batch_op.drop_column('ticket_sales')

    # ### end Alembic commands ###
