"""empty message

Revision ID: bf7d584153d7
Revises: b1a649714b81
Create Date: 2024-02-28 01:43:26.296364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7d584153d7'
down_revision = 'b1a649714b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EntryRequirement', sa.String(length=255), nullable=True))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TransactionID', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('Category', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('CreationDate', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.create_foreign_key(None, 'transactions', ['TransactionID'], ['TransactionID'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_PaymentMethodID_fkey', type_='foreignkey')
        batch_op.drop_constraint('transactions_TicketID_fkey', type_='foreignkey')
        batch_op.drop_column('TicketID')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Birthday', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('Birthday')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TicketID', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('transactions_TicketID_fkey', 'tickets', ['TicketID'], ['TicketID'])
        batch_op.create_foreign_key('transactions_PaymentMethodID_fkey', 'paymentmethods', ['PaymentMethodID'], ['PaymentMethodID'])

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('CreationDate')
        batch_op.drop_column('Category')
        batch_op.drop_column('TransactionID')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('EntryRequirement')

    # ### end Alembic commands ###
