"""empty message

Revision ID: f00c3bf9552d
Revises: da75827b78f9
Create Date: 2024-05-09 00:02:39.977566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00c3bf9552d'
down_revision = 'da75827b78f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('DiscountID', sa.UUID(), nullable=False),
    sa.Column('discount_type', sa.String(length=255), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('DiscountID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discounts')
    # ### end Alembic commands ###
