"""empty message

Revision ID: 91b6a51c4e6f
Revises: 
Create Date: 2024-02-09 09:27:36.630067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b6a51c4e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('LocationID', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('Capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('LocationID')
    )
    op.create_table('organizers',
    sa.Column('OrganizerID', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('ContactInfo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('OrganizerID')
    )
    op.create_table('users',
    sa.Column('UserID', sa.UUID(), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('FirstName', sa.String(length=255), nullable=False),
    sa.Column('LastName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('events',
    sa.Column('EventID', sa.UUID(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('LocationID', sa.UUID(), nullable=False),
    sa.Column('DateTime', sa.DateTime(), nullable=False),
    sa.Column('EndTime', sa.DateTime(), nullable=False),
    sa.Column('OrganizerID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['LocationID'], ['locations.LocationID'], ),
    sa.ForeignKeyConstraint(['OrganizerID'], ['organizers.OrganizerID'], ),
    sa.PrimaryKeyConstraint('EventID')
    )
    op.create_table('paymentmethods',
    sa.Column('PaymentMethodID', sa.UUID(), nullable=False),
    sa.Column('UserID', sa.UUID(), nullable=True),
    sa.Column('Provider', sa.String(length=255), nullable=True),
    sa.Column('PaymentDetails', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('PaymentMethodID')
    )
    op.create_table('tickets',
    sa.Column('TicketID', sa.UUID(), nullable=False),
    sa.Column('EventID', sa.UUID(), nullable=True),
    sa.Column('UserID', sa.UUID(), nullable=True),
    sa.Column('SeatNumber', sa.String(length=255), nullable=True),
    sa.Column('initialPrice', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Status', sa.Enum('Available', 'Sold', 'ListedonMarketplace', 'Admitted', name='Status'), nullable=True),
    sa.ForeignKeyConstraint(['EventID'], ['events.EventID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('TicketID')
    )
    op.create_table('marketplacelistings',
    sa.Column('ListingID', sa.UUID(), nullable=False),
    sa.Column('TicketID', sa.UUID(), nullable=True),
    sa.Column('SellerID', sa.UUID(), nullable=True),
    sa.Column('EventID', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['EventID'], ['events.EventID'], ),
    sa.ForeignKeyConstraint(['SellerID'], ['users.UserID'], ),
    sa.ForeignKeyConstraint(['TicketID'], ['tickets.TicketID'], ),
    sa.PrimaryKeyConstraint('ListingID')
    )
    op.create_table('transactions',
    sa.Column('TransactionID', sa.UUID(), nullable=False),
    sa.Column('TicketID', sa.UUID(), nullable=True),
    sa.Column('BuyerID', sa.UUID(), nullable=True),
    sa.Column('SellerID', sa.UUID(), nullable=True),
    sa.Column('PaymentMethodID', sa.UUID(), nullable=True),
    sa.Column('TransactionAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('TransactionDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['BuyerID'], ['users.UserID'], ),
    sa.ForeignKeyConstraint(['PaymentMethodID'], ['paymentmethods.PaymentMethodID'], ),
    sa.ForeignKeyConstraint(['SellerID'], ['users.UserID'], ),
    sa.ForeignKeyConstraint(['TicketID'], ['tickets.TicketID'], ),
    sa.PrimaryKeyConstraint('TransactionID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('marketplacelistings')
    op.drop_table('tickets')
    op.drop_table('paymentmethods')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('organizers')
    op.drop_table('locations')
    # ### end Alembic commands ###
