"""empty message

Revision ID: 9a97b0a652fb
Revises: 
Create Date: 2024-02-08 15:01:03.084841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a97b0a652fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('UserID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('Username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('PasswordHash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('PhoneNumber', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('UserID', name='users_pkey')
    )
    # ### end Alembic commands ###
